#!/usr/bin/env bash
# sync-env.sh — Generate .env.outputs from terraform outputs + Secrets Manager.
#
# Run this after every `terraform apply` to keep post-deploy env vars in sync.
# Usage:
#   cd <repo-root>
#   scripts/sync-env.sh [--profile <aws-profile>] [--region <aws-region>]
#
# Output:
#   .env.outputs  — sourced by loadenv.sh; never commit this file.
#
# Requirements: aws CLI, terraform, jq

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform"
OUT_FILE="$REPO_ROOT/.env.outputs"

# --- parse flags ---
AWS_PROFILE="${AWS_PROFILE:-nyk-tf}"
AWS_REGION="${AWS_REGION:-us-east-1}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) AWS_PROFILE="$2"; shift 2 ;;
    --region)  AWS_REGION="$2";  shift 2 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

export AWS_PROFILE AWS_REGION

echo "Fetching terraform outputs from $TF_DIR ..."
TF_OUT=$(terraform -chdir="$TF_DIR" output -json 2>/dev/null)

tf() { echo "$TF_OUT" | jq -r ".$1.value // empty"; }

# --- terraform outputs ---
REST_API_ENDPOINT=$(tf rest_api_endpoint)
APIGW_WEBSOCKET_ENDPOINT=$(tf websocket_endpoint)
RDS_PROXY_ENDPOINT=$(tf rds_proxy_endpoint)
DB_SECRET_ARN=$(tf db_secret_arn)
S3_BUCKET_EMAILS=$(tf s3_bucket_emails)
SQS_EMAIL_INBOUND_URL=$(tf sqs_email_inbound_url)
SQS_EMAIL_OUTBOUND_URL=$(tf sqs_email_outbound_url)
SQS_WEBHOOK_DELIVERY_URL=$(tf sqs_webhook_delivery_url)
SQS_WS_DISPATCH_URL=$(tf sqs_ws_dispatch_url)
SQS_EMBEDDER_URL=$(tf sqs_embedder_url)
SQS_SES_EVENTS_URL=$(tf ses_events_queue_url)

# TEST_API_KEY: read from .env Bootstrap key, used for integration tests
TEST_API_KEY=$(grep -E '^#\s*Key:\s*' "$REPO_ROOT/.env" 2>/dev/null | head -1 | sed 's/.*Key:[[:space:]]*//')

# --- database password from Secrets Manager ---
echo "Fetching DB credentials from Secrets Manager ($DB_SECRET_ARN) ..."
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$DB_SECRET_ARN" \
  --region "$AWS_REGION" \
  --query SecretString \
  --output text)
DB_PASSWORD=$(echo "$SECRET_JSON" | jq -r '.password')

# Reconstruct DATABASE_URL from outputs — read db_name/username from .env TF_VAR_* if present
DB_USERNAME="${TF_VAR_db_username:-$(grep -E '^TF_VAR_db_username=' "$REPO_ROOT/.env" 2>/dev/null | cut -d= -f2-)}"
DB_NAME="${TF_VAR_db_name:-$(grep -E '^TF_VAR_db_name=' "$REPO_ROOT/.env" 2>/dev/null | cut -d= -f2-)}"
DB_USERNAME="${DB_USERNAME:-ngxadmin}"
DB_NAME="${DB_NAME:-ngx}"

DATABASE_URL="postgres://${DB_USERNAME}:${DB_PASSWORD}@${RDS_PROXY_ENDPOINT}:5432/${DB_NAME}?sslmode=require"

# --- write .env.outputs ---
cat > "$OUT_FILE" <<EOF
# ============================================================
# .env.outputs — AUTO-GENERATED by scripts/sync-env.sh
# DO NOT EDIT MANUALLY. DO NOT COMMIT.
# Re-run scripts/sync-env.sh after terraform apply.
# Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# ============================================================

# PostgreSQL (Aurora via RDS Proxy)
DATABASE_URL=${DATABASE_URL}

# S3
S3_BUCKET=${S3_BUCKET_EMAILS}

# SQS
SQS_EMAIL_INBOUND_URL=${SQS_EMAIL_INBOUND_URL}
SQS_EMAIL_OUTBOUND_URL=${SQS_EMAIL_OUTBOUND_URL}
SQS_WEBHOOK_DELIVERY_URL=${SQS_WEBHOOK_DELIVERY_URL}
SQS_WS_DISPATCH_URL=${SQS_WS_DISPATCH_URL}
SQS_EMBEDDER_URL=${SQS_EMBEDDER_URL}
SQS_SES_EVENTS_URL=${SQS_SES_EVENTS_URL}

# API Gateway
REST_API_ENDPOINT=${REST_API_ENDPOINT}
APIGW_WEBSOCKET_ENDPOINT=${APIGW_WEBSOCKET_ENDPOINT}

# Integration test vars (maps prod resources to TEST_* names expected by go test ./tests/integration/...)
TEST_BASE_URL=${REST_API_ENDPOINT}
TEST_API_KEY=${TEST_API_KEY}
TEST_S3_BUCKET_EMAILS=${S3_BUCKET_EMAILS}
TEST_LAMBDA_PREFIX=ngx-prod
TEST_AWS_REGION=${AWS_REGION}
TEST_WS_URL=${APIGW_WEBSOCKET_ENDPOINT}
EOF

echo "Written: $OUT_FILE"
echo ""
echo "Source with:  source loadenv.sh"
